### ISSUE TITLE
`ConnectionError` was depricated and removed in kafka-python 2.x

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [robinhood/aiokafka#27]
https://github.com/robinhood/aiokafka/blob/10e4119104ee32b726ab750b3e7120a85d2c7f25/aiokafka/errors.py#L71 - this does not work in kafka-python 2.x
`ConnectionError` was depricated and removed in kafka-python 2.x

so right now faust is failing with this trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/faust", line 5, in <module>
    from faust.cli.faust import cli
  File "/usr/local/lib/python3.8/site-packages/faust/cli/faust.py", line 8, in <module>
    from .livecheck import livecheck
  File "/usr/local/lib/python3.8/site-packages/faust/cli/livecheck.py", line 3, in <module>
    from .worker import worker
  File "/usr/local/lib/python3.8/site-packages/faust/cli/worker.py", line 13, in <module>
    from faust.worker import Worker as FaustWorker
  File "/usr/local/lib/python3.8/site-packages/faust/worker.py", line 19, in <module>
    from aiokafka.structs import TopicPartition
  File "/usr/local/lib/python3.8/site-packages/aiokafka/__init__.py", line 4, in <module>
    from .client import AIOKafkaClient
  File "/usr/local/lib/python3.8/site-packages/aiokafka/client.py", line 10, in <module>
    import aiokafka.errors as Errors
  File "/usr/local/lib/python3.8/site-packages/aiokafka/errors.py", line 4, in <module>
    from kafka.errors import (
ImportError: cannot import name 'ConnectionError' from 'kafka.errors' (/usr/local/lib/python3.8/site-packages/kafka/errors.py)
```

**Comment by Rishi-jha** [comment]
PR for this fix

https://github.com/robinhood/aiokafka/pull/29
